language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 --slave /usr/bin/gcov gcov /usr/bin/gcov-4.8
  - sudo update-alternatives --set gcc /usr/bin/gcc-4.8
  - sudo pip install cpp-coveralls --use-mirrors
  - git clone https://github.com/dcoeurjo/cpp-coveralls.git

script:
  - cmake . && make 
  - ls -l
#  - ls -al CMakeFiles/prog1.dir  
#  - gcov -o CMakeFiles/prog1.dir/prog1.cpp.o x
#  - ls -al   

after_success:
  - make test
  - coveralls --verbose
